# must be unique in a given SonarQube instance
sonar.projectKey=mohkharma_llm-generated-code
sonar.gradle.skipCompile =true
# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=./src
sonar.java.binaries = ./build/classes/java/main
#sonar.exclusions=**/*.java
sonar.exclusions=src/main/java/*.java
#sonar.java.libraries=./lib
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.objc.file.suffixes=-
#sonar.host.url=http://localhost:9000/
sonar.host.url=https://sonarcloud.io
sonar.login=26a80b76d6ffb0882018173db8ff740172d21212
#sonar.login=sqp_63b20fb5ec12ee892ff5cddef124162a9e57bd93
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.python.version=3
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

