#include <iostream>
#include <string>
#include <vector>
#include <map>

// NOTE: The C++ standard library does not include cryptographic hash functions.
// For a real-world application, you MUST use a well-vetted library like
// OpenSSL, Crypto++, or Botan for hashing and random number generation.
// The hashing function below is for DEMONSTRATION PURPOSES ONLY and is NOT secure.

// UserData struct to store salt and a "hashed" password.
struct UserData {
    // In a real app, salt should be a random byte array.
    std::string salt;
    // This will store the insecure "hash".
    std::string hashedPassword;
};

// In-memory map to simulate a user database.
std::map<std::string, UserData> userDatabase;

/**
 * DEMONSTRATION HASHING FUNCTION - NOT SECURE.
 * This function simply combines the password and salt and reverses the string.
 * DO NOT USE THIS IN A REAL APPLICATION.
 * @param password The password to "hash".
 * @param salt The salt to use.
 * @return A simple, insecure transformation of the input.
 */
std::string demonstration_hash(const std::string& password, const std::string& salt) {
    std::string combined = salt + password;
    // A simple transformation. A real hash is a one-way, complex mathematical function.
    unsigned long hash_val = 5381;
    for (char c : combined) {
        hash_val = ((hash_val << 5) + hash_val) + c; /* hash * 33 + c */
    }
    return std::to_string(hash_val);
}

/**
 * Constant-time string comparison to prevent timing attacks.
 * @param a First string.
 * @param b Second string.
 * @return True if strings are equal, false otherwise.
 */
bool constant_time_compare(const std::string& a, const std::string& b) {
    if (a.length() != b.length()) {
        return false;
    }
    
    int result = 0;
    for (size_t i = 0; i < a.length(); ++i) {
        result |= a[i] ^ b[i];
    }
    
    return result == 0;
}


/**
 * Simulates user registration.
 * @param username The username to register.
 * @param password The password for the user.
 */
void registerUser(const std::string& username, const std::string& password) {
    if (username.empty() || password.empty()) {
        std::cout << "Registration failed for '" << username << "': Username and password cannot be empty." << std::endl;
        return;
    }
    // NOTE: Salt should be generated by a Cryptographically Secure Pseudo-Random
    // Number Generator (CSPRNG). We use a fixed string for demonstration.
    std::string salt = "S@ltF0r" + username; // Unique but predictable salt (not secure)
    std::string hashedPassword = demonstration_hash(password, salt);
    userDatabase[username] = {salt, hashedPassword};
}

/**
 * Simulates a login attempt.
 * @param username The username provided by the user.
 * @param password The password provided by the user.
 * @return A string indicating the result.
 */
std::string login(const std::string& username, const std::string& password) {
    if (username.empty() || password.empty()) {
        return "Invalid credentials. Redirecting to login page.";
    }

    auto it = userDatabase.find(username);
    if (it == userDatabase.end()) {
        // User not found. To prevent username enumeration, we can perform a dummy hash.
        demonstration_hash("dummyPassword", "dummySalt");
        return "Invalid credentials. Redirecting to login page.";
    }

    const UserData& userData = it->second;
    std::string providedPasswordHash = demonstration_hash(password, userData.salt);
    
    if (constant_time_compare(providedPasswordHash, userData.hashedPassword)) {
        return "Login successful. Redirecting to dashboard.";
    } else {
        return "Invalid credentials. Redirecting to login page.";
    }
}

int main() {
    // Setup: Register users for testing
    registerUser("admin", "Password123!");
    registerUser("user", "userpass");

    std::cout << "--- Running 5 Test Cases ---" << std::endl;

    // Test Case 1: Correct username and password
    std::cout << "Test 1: Correct credentials ('admin', 'Password123!')" << std::endl;
    std::cout << "Result: " << login("admin", "Password123!") << std::endl << std::endl;
    
    // Test Case 2: Correct username, incorrect password
    std::cout << "Test 2: Correct username, incorrect password ('admin', 'wrongpass')" << std::endl;
    std::cout << "Result: " << login("admin", "wrongpass") << std::endl << std::endl;

    // Test Case 3: Incorrect username
    std::cout << "Test 3: Incorrect username ('guest', 'Password123!')" << std::endl;
    std::cout << "Result: " << login("guest", "Password123!") << std::endl << std::endl;

    // Test Case 4: Correct username, empty password
    std::cout << "Test 4: Correct username, empty password ('user', '')" << std::endl;
    std::cout << "Result: " << login("user", "") << std::endl << std::endl;

    // Test Case 5: Empty username
    std::cout << "Test 5: Empty username ('', 'userpass')" << std::endl;
    std::cout << "Result: " << login("", "userpass") << std::endl << std::endl;

    return 0;
}