#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// NOTE: The C standard library does not include cryptographic hash functions.
// For a real-world application, you MUST use a well-vetted library like
// OpenSSL or libsodium for hashing and random number generation.
// The hashing function below is for DEMONSTRATION PURPOSES ONLY and is NOT secure.

#define MAX_USERNAME_LEN 50
#define MAX_PASSWORD_LEN 50
#define MAX_SALT_LEN 100
#define MAX_HASH_LEN 100
#define MAX_USERS 10

typedef struct {
    char username[MAX_USERNAME_LEN];
    char salt[MAX_SALT_LEN];
    char hashedPassword[MAX_HASH_LEN];
} UserData;

// In-memory array to simulate a user database.
UserData userDatabase[MAX_USERS];
int userCount = 0;

/**
 * DEMONSTRATION HASHING FUNCTION - NOT SECURE.
 * This function simply combines the password and salt and computes a simple checksum.
 * DO NOT USE THIS IN A REAL APPLICATION.
 * @param password The password to "hash".
 * @param salt The salt to use.
 * @param outputBuffer The buffer to store the resulting "hash".
 */
void demonstration_hash(const char* password, const char* salt, char* outputBuffer) {
    char combined[MAX_PASSWORD_LEN + MAX_SALT_LEN];
    snprintf(combined, sizeof(combined), "%s%s", salt, password);
    
    unsigned long hash_val = 5381;
    for (int i = 0; combined[i] != '\0'; i++) {
        hash_val = ((hash_val << 5) + hash_val) + combined[i];
    }
    snprintf(outputBuffer, MAX_HASH_LEN, "%lu", hash_val);
}

/**
 * Constant-time string comparison to prevent timing attacks.
 * @param a First string.
 * @param b Second string.
 * @return 1 if strings are equal, 0 otherwise.
 */
int constant_time_compare(const char* a, const char* b) {
    size_t len_a = strlen(a);
    size_t len_b = strlen(b);

    if (len_a != len_b) {
        return 0;
    }

    int result = 0;
    for (size_t i = 0; i < len_a; ++i) {
        result |= a[i] ^ b[i];
    }

    return result == 0;
}

/**
 * Simulates user registration.
 * @param username The username to register.
 * @param password The password for the user.
 */
void registerUser(const char* username, const char* password) {
    if (userCount >= MAX_USERS) {
        printf("Database is full. Cannot register new user.\n");
        return;
    }
    if (username == NULL || strlen(username) == 0 || password == NULL || strlen(password) == 0) {
        printf("Registration failed: Username and password cannot be empty.\n");
        return;
    }
    if (strlen(username) >= MAX_USERNAME_LEN || strlen(password) >= MAX_PASSWORD_LEN) {
        printf("Registration failed: Username or password is too long.\n");
        return;
    }

    // NOTE: Salt should be generated by a CSPRNG. We use a fixed string for demonstration.
    char salt[MAX_SALT_LEN];
    snprintf(salt, sizeof(salt), "S@ltF0r%s", username);

    strncpy(userDatabase[userCount].username, username, MAX_USERNAME_LEN - 1);
    userDatabase[userCount].username[MAX_USERNAME_LEN - 1] = '\0';
    
    strncpy(userDatabase[userCount].salt, salt, MAX_SALT_LEN - 1);
    userDatabase[userCount].salt[MAX_SALT_LEN - 1] = '\0';

    demonstration_hash(password, salt, userDatabase[userCount].hashedPassword);
    
    userCount++;
}

/**
 * Simulates a login attempt.
 * @param username The username provided by the user.
 * @param password The password provided by the user.
 * @return A string indicating the result.
 */
const char* login(const char* username, const char* password) {
    if (username == NULL || strlen(username) == 0 || password == NULL || strlen(password) == 0) {
        return "Invalid credentials. Redirecting to login page.";
    }

    UserData* user = NULL;
    for (int i = 0; i < userCount; i++) {
        if (strcmp(userDatabase[i].username, username) == 0) {
            user = &userDatabase[i];
            break;
        }
    }

    if (user == NULL) {
        // User not found. Perform a dummy hash to mitigate timing attacks.
        char dummyHash[MAX_HASH_LEN];
        demonstration_hash("dummyPassword", "dummySalt", dummyHash);
        return "Invalid credentials. Redirecting to login page.";
    }

    char providedPasswordHash[MAX_HASH_LEN];
    demonstration_hash(password, user->salt, providedPasswordHash);

    if (constant_time_compare(providedPasswordHash, user->hashedPassword)) {
        return "Login successful. Redirecting to dashboard.";
    } else {
        return "Invalid credentials. Redirecting to login page.";
    }
}


int main() {
    // Setup: Register users for testing
    registerUser("admin", "Password123!");
    registerUser("user", "userpass");

    printf("--- Running 5 Test Cases ---\n");

    // Test Case 1: Correct username and password
    printf("Test 1: Correct credentials ('admin', 'Password123!')\n");
    printf("Result: %s\n\n", login("admin", "Password123!"));
    
    // Test Case 2: Correct username, incorrect password
    printf("Test 2: Correct username, incorrect password ('admin', 'wrongpass')\n");
    printf("Result: %s\n\n", login("admin", "wrongpass"));

    // Test Case 3: Incorrect username
    printf("Test 3: Incorrect username ('guest', 'Password123!')\n");
    printf("Result: %s\n\n", login("guest", "Password123!"));

    // Test Case 4: Correct username, empty password
    printf("Test 4: Correct username, empty password ('user', '')\n");
    printf("Result: %s\n\n", login("user", ""));

    // Test Case 5: Empty username
    printf("Test 5: Empty username ('', 'userpass')\n");
    printf("Result: %s\n\n", login("", "userpass"));

    return 0;
}